# Code of Conduct

# Code of Conduct

## Introduction

We are committed to creating a friendly and respectful place for learning, teaching and contributing. All participants in our course and communications are expected to show respect and courtesy to others.

To make clear what is expected, everyone participating in SOCI 3040 activities is required to conform to the Code of Conduct. This Code of Conduct applies to all spaces managed by SOCI 3040 including, but not limited to, class meetings, email communication, and online forums such as Piazza and GitHub. The SOCI 3040 teaching team are expected to assist with the enforcement of the Code of Conduct.

The SOCI 3040 Instructor(s) is responsible for enforcing the Code of Conduct. All reports will be reviewed by the Instructor(s) and will be kept confidential.

## The SOCI 3040 Code of Conduct

We are dedicated to providing a welcoming and supportive environment for all people, regardless of background or identity. As such, we do not tolerate behaviour that is disrespectful to our teachers or learners or that excludes, intimidates, or causes discomfort to others. We do not tolerate discrimination or harassment based on characteristics that include, but are not limited to, gender identity and expression, sexual orientation, disability, physical appearance, body size, citizenship, nationality, ethnic or social origin, pregnancy, familial status, veteran status, genetic information, religion or belief (or lack thereof), membership of a national minority, property, age, education, socio-economic status, technical choices, and experience level.

Everyone who participates in SOCI 3040 activities is required to conform to this Code of Conduct. It applies to all spaces managed by SOCI 3040 including, but not limited to, class meetings, email communication, and online forums such as Piazza and GitHub. The SOCI 3040 teaching team are expected to assist with the enforcement of the Code of Conduct.

## Expected Behavior

All participants in our events and communications are expected to show respect and courtesy to others. All interactions should be professional regardless of platform: either online or in-person. In order to foster a positive and professional learning environment we encourage the following kinds of behaviours in all SOCI 3040 events and platforms:

- Use welcoming and inclusive language
- Be respectful of different viewpoints and experiences
- Gracefully accept constructive criticism
- Focus on what is best for the community
- Show courtesy and respect towards other community members

Note: See [the four social rules](https://www.recurse.com/manual#sub-sec-social-rules) for further recommendations.

## Unacceptable Behavior

Examples of unacceptable behavior by participants at any SOCI 3040 event/platform include:

- written or verbal comments which have the effect of excluding people on the basis of membership of any specific group
- causing someone to fear for their safety, such as through stalking, following, or intimidation
- violent threats or language directed against another person
- the display of sexual or violent images
- unwelcome sexual attention
- nonconsensual or unwelcome physical contact
- sustained disruption of talks, events or communications
- insults or put downs
- sexist, racist, homophobic, transphobic, ableist, or exclusionary jokes
- excessive swearing
- incitement to violence, suicide, or self-harm
- continuing to initiate interaction (including photography or recording) with someone after being asked to stop publication of private communication without consent
- Consequences of Unacceptable Behavior

Participants who are asked to stop any inappropriate behavior are expected to comply immediately. This applies to any SOCI 3040 events and platforms, either online or in-person. If a participant engages in behavior that violates this code of conduct, the teaching team may warn the offender and or engage the SOCI 3040 Instructor to investigate the Code of Conduct violation and impose appropriate sanctions.

## Incident Reporting Guidelines

If someone violates the Code of Conduct during a SOCI 3040 event or in an online space outside of organised events, we ask that you report it to the Instructor(s) in person (John McLevey), or in an email to <john.mclevey@uwaterloo.ca>.

## Attribution

Derived from the [DSCI 100 Code of Conduct](https://ubc-dsci.github.io/dsci-100-student/CODE_OF_CONDUCT.html), which was derived from the [Carpentries Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).