project:
  type: website
  render:
    - "*.qmd"
  output-dir: docs
  resources:
    - "media/"
    - "../references.bib"

website:
  site-url: "https://www.johnmclevey.com/quantitative-research-methods/"  
  repo-url: mclevey/quantitative-research-methods
  search:
    location: sidebar
    type: textbox
  comments: 
    giscus:
      repo: mclevey/quantitative-research-methods
      loading: lazy
      theme:
        light: light
        dark: dark_dimmed
  page-footer: 
    border: true
    center: "CC BY-SA"
    left: "[John McLevey](https://www.johnmclevey.com)" 
    right:
      - icon: github
        href: https://github.com/quantitative-research-methods
  body-footer: |
      <!-- Simple Analytics - 100% privacy-first analytics -->
      <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
      <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>


  title: "(SOCI 3040) Quantitative Research Methods"
  navbar:
    background: secondary
    left:
      - text: "Syllabus"
        href: pages/syllabus.qmd
      - text: "Slides"
        menu:
          - slides/deck-01.qmd
          - slides/deck-02.qmd
          - slides/deck-03.qmd
          - slides/deck-04.qmd
          - slides/deck-05.qmd
          - slides/deck-06.qmd
          - slides/deck-07.qmd
          - slides/deck-08.qmd
          - slides/deck-09.qmd
          - slides/deck-10.qmd
          - slides/deck-11.qmd
          - slides/deck-12.qmd
          - slides/deck-13.qmd
          - slides/deck-14.qmd
          - slides/deck-15.qmd
          - slides/deck-16.qmd
          - slides/deck-17.qmd
          - slides/deck-18.qmd
          - slides/deck-19.qmd
          - slides/deck-20.qmd
          - slides/deck-21.qmd
          - slides/deck-22.qmd
          - slides/deck-23.qmd
          - slides/deck-24.qmd
          - slides/deck-25.qmd
      - text: "Labs"
        menu:
          - pages/lab-instructions.qmd
          - text: "Lab 01 -- Telling stories with data"
            href: pages/lab-01.qmd
          - text: "Lab 02 -- Drinking from a firehose"
            href: pages/lab-02.qmd
          - text: "Lab 03 -- Reproducible workflows"
            href: pages/lab-03.qmd
          - text: "Lab 04 -- Communication"
            href: pages/lab-04.qmd
          - text: "Lab 05 -- Measurement, censuses, and sampling"
            href: pages/lab-05.qmd
          - text: "Lab 06 -- APIs, scraping, and parsing"
            href: pages/lab-06.qmd
          - text: "Lab 07 -- Experiments and surveys"
            href: pages/lab-07.qmd
          - text: "Lab 08 -- Working with Data"
            href: pages/lab-08.qmd
          - text: "Lab 09 -- Exploratory data analysis"
            href: pages/lab-09.qmd
          - text: "Lab 10 -- Linear models"
            href: pages/lab-10.qmd
          - text: "Lab 11 -- Generalized linear models"
            href: pages/lab-11.qmd
          - text: "Lab 12 -- Multilevel regression with post-stratification"
            href: pages/lab-12.qmd
      - text: "Cheatsheets"
        menu: 
          - pages/concepts.qmd
          - pages/diagrams.qmd
          - pages/workflow.qmd
          - pages/notation.qmd
      - text: "🔥 Telling Stories with Data"
        menu:
          - text: "📖 Book Website"
            href: https://tellingstorieswithdata.com/
          - text: "Ch. 01 -- Telling stories with data"
            href: https://tellingstorieswithdata.com/01-introduction.html
          - text: "Ch. 02 -- Drinking from a fire hose"
            href: https://tellingstorieswithdata.com/02-drinking_from_a_fire_hose.html
          - text: "Ch. 03 -- Reproducible workflows"
            href: https://tellingstorieswithdata.com/03-workflow.html
          - text: "Ch. 04 -- Writing research"
            href: https://tellingstorieswithdata.com/04-writing_research.html
          - text: "Ch. 05 -- Graphs, tables, and maps"
            href: https://tellingstorieswithdata.com/05-static_communication.html
          - text: "Ch. 06 -- Measurement, censuses, and sampling"
            href: https://tellingstorieswithdata.com/06-farm.html
          - text: "Ch. 07 -- APIs, scraping, and parsing"
            href: https://tellingstorieswithdata.com/07-gather.html
          - text: "Ch. 08 -- Experiments and surveys"
            href: https://tellingstorieswithdata.com/08-hunt.html
          - text: "Ch. 09 -- Clean and prepare"
            href: https://tellingstorieswithdata.com/09-clean_and_prepare.html
          - text: "Ch. 10 -- Store and share"
            href: https://tellingstorieswithdata.com/10-store_and_share.html
          - text: "Ch. 11 -- Exploratory data analysis"
            href: https://tellingstorieswithdata.com/11-eda.html
          - text: "Ch. 12 -- Linear models"
            href: https://tellingstorieswithdata.com/12-ijalm.html
          - text: "Ch. 13 -- Generalized Linear Models"
            href: https://tellingstorieswithdata.com/13-ijaglm.html
          - text: "Ch. 14 -- Prediction"
            href: https://tellingstorieswithdata.com/13-prediction.html
          - text: "Ch. 15 -- Causality from observational data"
            href: Causality from observational data
          - text: "Ch. 16 -- Multilevel regression with post-stratification"
            href: https://tellingstorieswithdata.com/15-mrp.html
          - text: "Ch. 17 -- Text as data"
            href: https://tellingstorieswithdata.com/16-text.html
          - text: "Ch. 18 -- Concluding remarks"
            href:  https://tellingstorieswithdata.com/17-concluding.html
          - text: "Appendix -- R essentials"
            href: https://tellingstorieswithdata.com/20-r_essentials.html
          - text: "Appendix -- Datasets"
            href: https://tellingstorieswithdata.com/21-datasets.html
          - text: "Appendix -- Interaction"
            href: https://tellingstorieswithdata.com/24-interaction.html
          - text: "Appendix -- Datasheets"
            href: https://tellingstorieswithdata.com/25-datasheet.html
          - text: "Appendix -- Production"
            href: https://tellingstorieswithdata.com/28-deploy.html
    right:
      - text: "**CC BY-SA**"
        href: https://creativecommons.org/licenses/by-sa/4.0/deed.en
      - icon: github
        href: https://github.com/
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "<strong>COMPUTING</strong>"
        href: pages/computing.qmd
      - section: "<strong>NOTES & MATERIALS</strong>"
        contents:
          - text: "Class 01. Tues Jan 07"
            href: pages/class-01.qmd
          - text: "Class 02. Thur Jan 09"
            href: pages/class-02.qmd
          - text: "Class 03. Tues Jan 14"
            href: pages/class-03.qmd
          - text: "Class 04. Thur Jan 16"
            href: pages/class-04.qmd
          - text: "Class 05. Tues Jan 21"
            href: pages/class-05.qmd
          - text: "Class 06. Thur Jan 23"
            href: pages/class-06.qmd
          - text: "Class 07. Tues Jan 28"
            href: pages/class-07.qmd
          - text: "Class 08. Thur Jan 30"
            href: pages/class-08.qmd
          - text: "Class 09. Tues Feb 04"
            href: pages/class-09.qmd
          - text: "Class 10. Thur Feb 06"
            href: pages/class-10.qmd
          - text: "Class 11. Tues Feb 11"
            href: pages/class-11.qmd
          - text: "Class 12. Thur Feb 13"
            href: pages/class-12.qmd
          - text: "Class 13. Tues Feb 18"
            href: pages/class-13.qmd
          - text: "Class 14. Thur Feb 20"
            href: pages/class-14.qmd
          - text: "Winter Break (Feb 23 - Mar 03)"
          # WINTER BREAK RUNS FEB 23 - MAR 03 
          - text: "Class 15. Tues Mar 04"
            href: pages/class-15.qmd
          - text: "Class 16. Thur Mar 06"
            href: pages/class-16.qmd
          - text: "Class 17. Tues Mar 11"
            href: pages/class-17.qmd
          - text: "Class 18. Thur Mar 13"
            href: pages/class-18.qmd
          - text: "Class 19. Tues Mar 18"
            href: pages/class-19.qmd
          - text: "Class 20. Thur Mar 20"
            href: pages/class-20.qmd
          - text: "Class 21. Tues Mar 25"
            href: pages/class-21.qmd
          - text: "Class 22. Thur Mar 27"
            href: pages/class-22.qmd
          - text: "Class 23. Tues Apr 01"
            href: pages/class-23.qmd
          - text: "Class 24. Thur Apr 03"
            href: pages/class-24.qmd
          - text: "Class 25. Tues Apr 08"
            href: pages/class-25.qmd
      - text: Student Wellness and Counselling Centre
        href: https://www.mun.ca/studentwellness/
      - text: Academic Success Centre
        href: https://www.mun.ca/munup/academic-success-centre/
      - text: Accessibility Services
        href: https://www.mun.ca/munup/academic-success-centre/learning-supports/accessibility-services/

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    mermaid:
      theme: default