project:
  type: website
  render:
    - "*.qmd"
  output-dir: docs
  resources:
    - "media/"
    - "../references.bib"

website:
  site-url: "https://www.johnmclevey.com/quantitative-research-methods/"  
  repo-url: mclevey/quantitative-research-methods
  search:
    location: sidebar
    type: textbox
  comments: 
    giscus:
      repo: mclevey/quantitative-research-methods
      loading: lazy
      theme:
        light: light
        dark: dark_dimmed
  page-footer: 
    border: true
    center: "CC BY-SA"
    left: "[John McLevey](https://www.johnmclevey.com)" 
    right:
      - icon: github
        href: https://github.com/mclevey
  body-footer: |
      <!-- Simple Analytics - 100% privacy-first analytics -->
      <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
      <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
  # google-analytics: # EXAMPLE: "G-3Z3Z3Z3Z3Z3"



  title: "(SOCI 3040) Quantitative Research Methods"
  navbar:
    background: secondary
    left:
      - text: "Syllabus"
        href: pages/syllabus.qmd
      - text: "Classes"
        menu:
          - pages/lecture-01.qmd
          - pages/lecture-02.qmd
          - pages/lecture-03.qmd
          - pages/lecture-04.qmd
          - pages/lecture-05.qmd
          - pages/lecture-06.qmd
          - pages/lecture-07.qmd
          - pages/lecture-08.qmd
          - pages/lecture-09.qmd
          - pages/lecture-10.qmd
          - pages/lecture-11.qmd
          - pages/lecture-12.qmd
      - text: "Labs"
        menu:
          - labs/instructions.qmd
          - text: "Lab 01 -- Telling stories with data"
            href: labs/lab-01.qmd
          - text: "Lab 02 -- Drinking from a firehose"
            href: labs/lab-02.qmd
          - text: "Lab 03 -- Reproducible workflows"
            href: labs/lab-03.qmd
          - text: "Lab 04 -- Communication"
            href: labs/lab-04.qmd
          - text: "Lab 05 -- Measurement, censuses, and sampling"
            href: labs/lab-05.qmd
          - text: "Lab 06 -- APIs, scraping, and parsing"
            href: labs/lab-06.qmd
          - text: "Lab 07 -- Experiments and surveys"
            href: labs/lab-07.qmd
          - text: "Lab 08 -- Working with Data"
            href: labs/lab-08.qmd
          - text: "Lab 09 -- Exploratory data analysis"
            href: labs/lab-09.qmd
          - text: "Lab 10 -- Linear models"
            href: labs/lab-10.qmd
          - text: "Lab 11 -- Generalized linear models"
            href: labs/lab-11.qmd
          - text: "Lab 12 -- Multilevel regression with post-stratification"
            href: labs/lab-12.qmd
      - text: "Computing"
        menu:
          - text: "R and RStudio"
            href: https://posit.co/download/rstudio-desktop/
          - text: "Quarto"
            href: https://quarto.org
          - text: "Git"
            href: https://git-scm.com/downloads
          - text: "GitHub"
            href: https://www.github.com
          - text: "Posit Cloud"
            href: https://posit.cloud/
          - text: "API Keys"
            href: pages/keys.qmd
      - text: "🔥 Telling Stories with Data"
        menu:
          - text: "📖 Book Website"
            href: https://tellingstorieswithdata.com/
          - text: "Ch. 01 -- Telling stories with data"
            href: https://tellingstorieswithdata.com/01-introduction.html
          - text: "Ch. 02 -- Drinking from a fire hose"
            href: https://tellingstorieswithdata.com/02-drinking_from_a_fire_hose.html
          - text: "Ch. 03 -- Reproducible workflows"
            href: https://tellingstorieswithdata.com/03-workflow.html
          - text: "Ch. 04 -- Writing research"
            href: https://tellingstorieswithdata.com/04-writing_research.html
          - text: "Ch. 05 -- Graphs, tables, and maps"
            href: https://tellingstorieswithdata.com/05-static_communication.html
          - text: "Ch. 06 -- Measurement, censuses, and sampling"
            href: https://tellingstorieswithdata.com/06-farm.html
          - text: "Ch. 07 -- APIs, scraping, and parsing"
            href: https://tellingstorieswithdata.com/07-gather.html
          - text: "Ch. 08 -- Experiments and surveys"
            href: https://tellingstorieswithdata.com/08-hunt.html
          - text: "Ch. 09 -- Clean and prepare"
            href: https://tellingstorieswithdata.com/09-clean_and_prepare.html
          - text: "Ch. 10 -- Store and share"
            href: https://tellingstorieswithdata.com/10-store_and_share.html
          - text: "Ch. 11 -- Exploratory data analysis"
            href: https://tellingstorieswithdata.com/11-eda.html
          - text: "Ch. 12 -- Linear models"
            href: https://tellingstorieswithdata.com/12-ijalm.html
          - text: "Ch. 13 -- Generalized Linear Models"
            href: https://tellingstorieswithdata.com/13-ijaglm.html
          - text: "Ch. 14 -- Prediction"
            href: https://tellingstorieswithdata.com/13-prediction.html
          - text: "Ch. 15 -- Causality from observational data"
            href: Causality from observational data
          - text: "Ch. 16 -- Multilevel regression with post-stratification"
            href: https://tellingstorieswithdata.com/15-mrp.html
          - text: "Ch. 17 -- Text as data"
            href: https://tellingstorieswithdata.com/16-text.html
          - text: "Ch. 18 -- Concluding remarks"
            href:  https://tellingstorieswithdata.com/17-concluding.html
          - text: "Appendix -- R essentials"
            href: https://tellingstorieswithdata.com/20-r_essentials.html
          - text: "Appendix -- Datasets"
            href: https://tellingstorieswithdata.com/21-datasets.html
          - text: "Appendix -- Interaction"
            href: https://tellingstorieswithdata.com/24-interaction.html
          - text: "Appendix -- Datasheets"
            href: https://tellingstorieswithdata.com/25-datasheet.html
          - text: "Appendix -- Production"
            href: https://tellingstorieswithdata.com/28-deploy.html
      - text: "Cheatsheets"
        menu: 
          - pages/concepts.qmd
          - pages/diagrams.qmd
          - pages/workflow.qmd
          # - pages/notation.qmd
    right:
      - text: "Campus Resources"
        menu:
          - text: Student Wellness and Counselling Centre
            href: https://www.mun.ca/studentwellness/
          - text: Accessibility Services
            href: https://www.mun.ca/munup/academic-success-centre/learning-supports/accessibility-services/
          - text: Academic Success Centre
            href: https://www.mun.ca/munup/academic-success-centre/
          - text: Learning Skills Resources
            href: https://www.mun.ca/munup/academic-success-centre/learning-skills-resources/
          - text: Writing Centre
            href: https://www.mun.ca/munup/academic-success-centre/learning-supports/writing-and-research/
        # href: pages/resources.qmd
      - text: "Code of Conduct"
        href: pages/code-of-conduct.qmd
      - text: "**CC BY-SA**"
        href: https://creativecommons.org/licenses/by-sa/4.0/deed.en
      - icon: github
        href: https://github.com/
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "<strong>DAY BY DAY</strong>"
        contents:
          - text: "Tuesday, January 7"
            href: https://www.johnmclevey.com
          - text: "Thursday, January 9"
            href: https://www.johnmclevey.com
          - text: "Tuesday, January 14"
            href: https://www.johnmclevey.com
          - text: "Thursday, January 16"
            href: https://www.johnmclevey.com
          - text: "Tuesday, January 21"
            href: https://www.johnmclevey.com
          - text: "Thursday, January 23"
            href: https://www.johnmclevey.com
          - text: "Tuesday, January 28"
            href: https://www.johnmclevey.com
          - text: "Thursday, January 30"
            href: https://www.johnmclevey.com
          - text: "Tuesday, February 4"
            href: https://www.johnmclevey.com
          - text: "Thursday, February 6"
            href: https://www.johnmclevey.com
          - text: "Tuesday, February 11"
            href: https://www.johnmclevey.com
          - text: "Thursday, February 13"
            href: https://www.johnmclevey.com
          - text: "Tuesday, February 18"
            href: https://www.johnmclevey.com
          - text: "Thursday, February 20"
            href: https://www.johnmclevey.com
          - text: "<strong>Winter Break!</strong>"
          # - text: "Tuesday, February 25"
          #   href: https://www.johnmclevey.com
          # - text: "Thursday, February 27"
          #   href: https://www.johnmclevey.com
          - text: "Tuesday, March 4"
            href: https://www.johnmclevey.com
          - text: "Thursday, March 6"
            href: https://www.johnmclevey.com
          - text: "Tuesday, March 11"
            href: https://www.johnmclevey.com
          - text: "Thursday, March 13"
            href: https://www.johnmclevey.com
          - text: "Tuesday, March 18"
            href: https://www.johnmclevey.com
          - text: "Thursday, March 20"
            href: https://www.johnmclevey.com
          - text: "Tuesday, March 25"
            href: https://www.johnmclevey.com
          - text: "Thursday, March 27"
            href: https://www.johnmclevey.com
          - text: "Tuesday, April 1"
            href: https://www.johnmclevey.com
          - text: "Thursday, April 3"
            href: https://www.johnmclevey.com
          - text: "Tuesday, April 8"
            href: https://www.johnmclevey.com



format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    mermaid:
      theme: default