@tbl-assessment provides an overview of assessment methods used in the course. More details are available below.

- **TODO**: Statistics Journal
- **TODO**: Required / Recommended readings in addition to TSWD (used in the labs so far...)

| Week | Assignment | Due Date | Value |
|:----|:-----------|:---------|:------|
| 01/12 | [Lab Notebook](../labs/lab-week-01/index.qmd) | xxxx | 6% |
| 02/12 | [Lab Notebook](../labs/lab-week-02/index.qmd) | xxxx | 6% |
| 03/12 | [Lab Notebook](../labs/lab-week-03/index.qmd) | xxxx | 6% |
| 04/12 | [Lab Notebook](../labs/lab-week-04/index.qmd) | xxxx | 6% |
| 05/12 | [Lab Notebook](../labs/lab-week-05/index.qmd) | xxxx | 6% |
| 06/12 | [Lab Notebook](../labs/lab-week-06/index.qmd) | xxxx | 6% |
| 07/12 | [Lab Notebook](../labs/lab-week-07/index.qmd) | xxxx | 6% |
| 08/12 | [Lab Notebook](../labs/lab-week-08/index.qmd) | xxxx | 6% |
| 09/12 | [Lab Notebook](../labs/lab-week-09/index.qmd) | xxxx | 8% |
| 10/12 | [Lab Notebook](../labs/lab-week-10/index.qmd) | xxxx | 8% |
| 11/12 | [Lab Notebook](../labs/lab-week-11/index.qmd) | xxxx | 8% |
| 12/12 | [Lab Notebook](../labs/lab-week-12/index.qmd) | xxxx | 8% |
| | Final Exam | xxxx | 20% |

: Learning Assessments {#tbl-assessment .striped}

### Weekly Lab Notebooks (80%)

Coming soon...

### Final Exam (20%)

Coming soon...
