# Course Schedule

@tbl-schedule provides a high-level overview of the course schedule with links to the slides and assigned readings for each class. Note that all class meetings will combine lectures with lab work, which will often be done collaboratively in groups of 2-3. **Please make sure to bring a fully charged laptop (anything is fine) or tablet to class.** If that is not possible, please speak to me as soon as possible so we can work out another arrangement.


| Module                       | Date      | Topic                                                   | Course Materials                                                                                                                                                |
|:-----------------------------|:----------|:--------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [01](../pages/lecture-01.qmd) | X-XX-XXXX | **Telling Stories with Data**                           | [Reading](https://tellingstorieswithdata.com/01-introduction.html), [Lecture](../slides/deck-01.qmd), [Lab](../pages/lab-week-01/index.qmd)               |
|                              | X-XX-XXXX | **Telling Stories with Data**                           | [Reading](https://tellingstorieswithdata.com/01-introduction.html), [Lecture](../slides/deck-01.qmd), [Lab](../pages/lab-week-01/index.qmd)               |
| [02](../pages/lecture-02.qmd) | X-XX-XXXX | **Drinking from a Firehose**                            | [Reading](https://tellingstorieswithdata.com/02-drinking_from_a_fire_hose.html), [Lecture](../slides/deck-02.qmd), [Lab](../pages/lab-week-02/index.qmd)  |
|                              | X-XX-XXXX | **Drinking from a Firehose**                            | [Reading](https://tellingstorieswithdata.com/02-drinking_from_a_fire_hose.html), [Lecture](../slides/deck-02.qmd), [Lab](../pages/lab-week-02/index.qmd)  |
| [03](../pages/lecture-03.qmd) | X-XX-XXXX | **Reproducible Workflows**                              | [Reading](https://tellingstorieswithdata.com/03-workflow.html), [Lecture](../slides/deck-03.qmd), [Lab](../pages/lab-week-03/index.qmd)                   |
|                              | X-XX-XXXX | **Reproducible Workflows**                              | [Reading](https://tellingstorieswithdata.com/03-workflow.html), [Lecture](../slides/deck-03.qmd), [Lab](../pages/lab-week-03/index.qmd)                   |
| [04](../pages/lecture-04.qmd) | X-XX-XXXX | **Writing Quantitative Manuscripts**                    | [Reading](https://tellingstorieswithdata.com/04-writing_research.html), [Lecture](../slides/deck-04.qmd), [Lab](../pages/lab-week-04/index.qmd)           |
|                              | X-XX-XXXX | **Graphs, Tables, Maps**                                | [Reading](https://tellingstorieswithdata.com/05-static_communication.html), [Lecture](../slides/deck-04.qmd), [Lab](../pages/lab-week-04/index.qmd)       |
| [05](../pages/lecture-05.qmd) | X-XX-XXXX | **Measurement & Sampling**                              | [Reading](https://tellingstorieswithdata.com/06-farm.html), [Lecture](../slides/deck-05.qmd), [Lab](../pages/lab-week-05/index.qmd)                       |
|                              | X-XX-XXXX | **Measurement & Sampling**                              | [Reading](https://tellingstorieswithdata.com/06-farm.html), [Lecture](../slides/deck-05.qmd), [Lab](../pages/lab-week-05/index.qmd)                       |
| [06](../pages/lecture-06.qmd) | X-XX-XXXX | **APIs, Scraping, & Parsing**                           | [Reading](https://tellingstorieswithdata.com/07-gather.html), [Lecture](../slides/deck-06.qmd), [Lab](../pages/lab-week-06/index.qmd)                     |
|                              | X-XX-XXXX | **APIs, Scraping, & Parsing**                           | [Reading](https://tellingstorieswithdata.com/07-gather.html), [Lecture](../slides/deck-06.qmd), [Lab](../pages/lab-week-06/index.qmd)                     |
| [07](../pages/lecture-07.qmd) | X-XX-XXXX | **Experiments & Surveys**                               | [Reading](https://tellingstorieswithdata.com/08-hunt.html), [Lecture](../slides/deck-07.qmd), [Lab](../pages/lab-week-07/index.qmd)                       |
|                              | X-XX-XXXX | **Experiments & Surveys**                               | [Reading](https://tellingstorieswithdata.com/08-hunt.html), [Lecture](../slides/deck-07.qmd), [Lab](../pages/lab-week-07/index.qmd)                       |
| [08](../pages/lecture-08.qmd) | X-XX-XXXX | **Cleaning and Preparing Data**                         | [Reading](https://tellingstorieswithdata.com/09-clean_and_prepare.html), [Lecture](../slides/deck-08.qmd), [Lab](../pages/lab-week-08/index.qmd)          |
|                              | X-XX-XXXX | **Storing and Sharing Data**                            | [Reading](https://tellingstorieswithdata.com/10-store_and_share.html), [Lecture](../slides/deck-08.qmd), [Lab](../pages/lab-week-08/index.qmd)            |
| [09](../pages/lecture-09.qmd) | X-XX-XXXX | **Exploratory Data Analysis**                           | [Reading](https://tellingstorieswithdata.com/11-eda.html), [Lecture](../slides/deck-09.qmd), [Lab](../pages/lab-week-09/index.qmd)                        |
|                              | X-XX-XXXX | **Exploratory Data Analysis**                           | [Reading](https://tellingstorieswithdata.com/11-eda.html), [Lecture](../slides/deck-09.qmd), [Lab](../pages/lab-week-09/index.qmd)                        |
| [10](../pages/lecture-10.qmd) | X-XX-XXXX | **Linear Models**                                       | [Reading](https://tellingstorieswithdata.com/12-ijalm.html), [Lecture](../slides/deck-10.qmd), [Lab](../pages/lab-week-10/index.qmd)                      |
|                              | X-XX-XXXX | **Multilevel Models**                                   | [Reading](https://tellingstorieswithdata.com/13-ijaglm.html#multilevel-modeling), [Lecture](../slides/deck-10.qmd), [Lab](../pages/lab-week-10/index.qmd) |
| [11](../pages/lecture-11.qmd) | X-XX-XXXX | **Generalized Linear Models (GLMs)**                    | [Reading](https://tellingstorieswithdata.com/13-ijaglm.html), [Lecture](../slides/deck-11.qmd), [Lab](../pages/lab-week-11/index.qmd)                     |
|                              | X-XX-XXXX | **Generalized Linear Models (GLMs)**                    | [Reading](https://tellingstorieswithdata.com/13-ijaglm.html), [Lecture](../slides/deck-11.qmd), [Lab](../pages/lab-week-11/index.qmd)                     |
| [12](../pages/lecture-12.qmd) | X-XX-XXXX | **Causality with Observational Data**                   | [Reading](https://tellingstorieswithdata.com/14-causality_from_obs.html), [Lecture](../slides/deck-12.qmd), [Lab](../pages/lab-week-12/index.qmd)         |
|                              | X-XX-XXXX | **Multilevel Regression with Poststratification (MRP)** | [Reading](https://tellingstorieswithdata.com/15-mrp.html), [Lecture](../slides/deck-12.qmd), [Lab](../pages/lab-week-12/index.qmd)                        |

: SOCI 3040 Course Schedule {#tbl-schedule .striped}